proc reset(): string {.procvar.} = "\e[0m"

# foreground colors
proc fgRed*(s: string): string {.procvar.} = "\e[31m" & s & reset()
proc fgBlack*(s: string): string {.procvar.} = "\e[30m" & s & reset()
proc fgGreen*(s: string): string {.procvar.} = "\e[32m" & s & reset()
proc fgYellow*(s: string): string {.procvar.} = "\e[33m" & s & reset()
proc fgBlue*(s: string): string {.procvar.} = "\e[34m" & s & reset()
proc fgMagenta*(s: string): string {.procvar.} = "\e[35m" & s & reset()
proc fgCyan*(s: string): string {.procvar.} = "\e[36m" & s & reset()
proc fgLightGray*(s: string): string {.procvar.} = "\e[37m" & s & reset()
proc fgDarkGray*(s: string): string {.procvar.} = "\e[90m" & s & reset()
proc fgLightRed*(s: string): string {.procvar.} = "\e[91m" & s & reset()
proc fgLightGreen*(s: string): string {.procvar.} = "\e[92m" & s & reset()
proc fgLightYellow*(s: string): string {.procvar.} = "\e[93m" & s & reset()
proc fgLightBlue*(s: string): string {.procvar.} = "\e[94m" & s & reset()
proc fgLightMagenta*(s: string): string {.procvar.} = "\e[95m" & s & reset()
proc fgLightCyan*(s: string): string {.procvar.} = "\e[96m" & s & reset()
proc fgWhite*(s: string): string {.procvar.} = "\e[97m" & s & reset()

# background colors
proc bgBlack*(s: string): string {.procvar.} = "\e[41m" & s & reset()
proc bgRed*(s: string): string {.procvar.} = "\e[41m" & s & reset()
proc bgGreen*(s: string): string {.procvar.} = "\e[42m" & s & reset()
proc bgYellow*(s: string): string {.procvar.} = "\e[43m" & s & reset()
proc bgBlue*(s: string): string {.procvar.} = "\e[44m" & s & reset()
proc bgMagenta*(s: string): string {.procvar.} = "\e[45m" & s & reset()
proc bgCyan*(s: string): string {.procvar.} = "\e[46m" & s & reset()
proc bgLightGray*(s: string): string {.procvar.} = "\e[47m" & s & reset()
proc bgDarkGray*(s: string): string {.procvar.} = "\e[100m" & s & reset()
proc bgLightRed*(s: string): string {.procvar.} = "\e[101m" & s & reset()
proc bgLightGreen*(s: string): string {.procvar.} = "\e[102m" & s & reset()
proc bgLightYellow*(s: string): string {.procvar.} = "\e[103m" & s & reset()
proc bgLightBlue*(s: string): string {.procvar.} = "\e[104m" & s & reset()
proc bgLightMagenta*(s: string): string {.procvar.} = "\e[105m" & s & reset()
proc bgLightCyan*(s: string): string {.procvar.} = "\e[106m" & s & reset()
proc bgWhite*(s: string): string {.procvar.} = "\e[107m" & s & reset()

# formatting functions
proc bold*(s: string): string {.procvar.} = "\e[1m" & s & reset()
proc underline*(s: string): string {.procvar.} = "\e[4m" & s & reset()
proc hidden*(s: string): string {.procvar.} = "\e[8m" & s & reset()
proc invert*(s: string): string {.procvar.} = "\e[7m" & s & reset()